services:
  db:
    image: postgres:16-alpine
    container_name: forsatech-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forsatech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: forsatech-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: forsatech
      JWT_SECRET: super-secret-forsatech-key
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: forsatech-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: forsatech-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
